server:
  port: 8080
spring:
  application:
    name: spring-mongodb
  profiles:
    active:
      - local

---

spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      authentication-database: admin
      username: ${USERNAME}
      password: ${PASSWORD}
      database: ${NAME_DATABASE}
      port: 27017
      host: localhost
